name: Build Packages

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: |
            requirements.txt

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            ruby ruby-dev rubygems build-essential \
            libunwind-dev \
            libxcb-xinerama0 \
            libxcb-cursor0
          sudo gem install --no-document fpm

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller==5.13.2

      - name: Build binaries
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          pyinstaller -s -F --hidden-import=ctypes --collect-all scapy server/tuxcutd.py
          pyinstaller -s -F --hidden-import=ctypes --collect-all dearpygui client/tuxcut.py

      - name: Prepare package files
        run: |
          rm -rf pkg/opt/tuxcut/*
          mv dist/tuxcut pkg/opt/tuxcut/
          mv dist/tuxcutd pkg/opt/tuxcut/

      - name: Get version
        id: get_version
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/v}
          else
            VERSION=$(date +'%Y.%m.%d')
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Build DEB package
        run: |
          fpm -s dir -t deb \
            -n tuxcut \
            -v ${{ steps.get_version.outputs.version }} \
            --iteration 1 \
            -d "libpcap0.8" \
            -d "arptables" \
            -d "dnsutils" \
            -d "net-tools" \
            -d "libxcb-xinerama0" \
            -d "libxcb-cursor0" \
            -C pkg

      - name: Build RPM package
        run: |
          fpm -s dir -t rpm \
            -n tuxcut \
            -v ${{ steps.get_version.outputs.version }} \
            --iteration 1 \
            -d "libpcap" \
            -d "arptables" \
            -d "bind-utils" \
            -d "net-tools" \
            -d "libxcb-xinerama0" \
            -d "libxcb-cursor0" \
            -C pkg

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: packages
          path: |
            *.deb
            *.rpm

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            *.deb
            *.rpm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 